name: 'Branch name based PR checklists'
description: 'Submit a comment to a PR base on the branch name.'
inputs:
  token:
    description: "Your GITHUB_TOKEN secret for API interactions."
    required: true
  template_dir:
    description: "The directory where text/markdown templates are placed."
    required: true
  mapping:
    description: "The mapping between branch name patterns and PR templates."
    required: true
  default:
    description: "The template to use when a branch name matches no patterns."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: "check-circle"
  color: "purple"